const {
        PROJECT_ID,
        API_KEY,
        DATABASE_ID ,
        PATIENT_COLLECTION_ID,
        DOCTORS_COLLECTION_ID,
        APPOINTMENT_COLLECTION_ID,
        NEXT_PUBLIC_BUCKET_ID: BUCKET_ID,  
        NEXT_PUBLIC_ENDPOINT: ENDPOINT
    } = process.env