import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from '../../lib/utils'
const inter = Inter({ subsets: ["latin"] });
import { ThemeProvider } from "@/components/theme-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`min-h-screen bg-dark-300 font-sans antialiased`)}>

      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          >
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
